package com.example.sudoku.solver.ui


enum class SquareType {
    NORMAL_SQUARE,

    SELECTED_SQUARE,
    AFFECTED_SQUARE,

    ROW_CLUE_SQUARE_TOP,
    ROW_CLUE_SQUARE_BOTTOM,
    ROW_CLUE_SQUARE_LAST_ROW,
    HIGHLIGHTED_ORANGE_SQUARE_ROW_TOP,
    HIGHLIGHTED_ORANGE_SQUARE_LAST_ROW,

    COLUMN_CLUE_SQUARE_LEFT,
    COLUMN_CLUE_SQUARE_RIGHT,
    COLUMN_CLUE_SQUARE_LAST_COLUMN,
    HIGHLIGHTED_ORANGE_SQUARE_COLUMN_LEFT,
    HIGHLIGHTED_ORANGE_SQUARE_LAST_COLUMN
}

enum class LastFreeCellClueLayout {
    ROW,
    COLUMN,
    SQUARE,
    NO_LAYOUT
}